#!/usr/bin/env python3
"""Generate LVGL CJK font using Pillow for rendering - guaranteed coverage."""
from PIL import Image, ImageDraw, ImageFont
import struct, os

INPUT = r"C:\Windows\Fonts\simhei.ttf"
OUTPUT = r"src\lv_font_mshy_16.c"
SIZE = 16
BPP = 4
NAME = "lv_font_mshy_16"

# All chars from source code + critical ones
CHARS = sorted(set(
    "中于件作保停入关列到刷前动双取口号启器在地型处天存安将已常开当径待志态息户找技拖择接搜操文新无日时显暂未本术机板查标栈栏桌检模止正测源滤灰版状理电知示移空窗端管索红绿置聊自色获行表装规言设词语误账路输过运连选配错键闲面题黄"
    "任务服处理列表"
))

def render_char(c, size):
    """Render a character, return (bitmap_bytes, w, h, bx, by, adv) or None."""
    font = ImageFont.truetype(INPUT, size)
    bbox = font.getbbox(c)
    if not bbox or (bbox[2]-bbox[0]) <= 0 or (bbox[3]-bbox[1]) <= 0:
        return None
    
    w = bbox[2] - bbox[0]
    h = bbox[3] - bbox[1]
    img = Image.new('L', (w, h), 0)
    d = ImageDraw.Draw(img)
    d.text((-bbox[0], -bbox[1]), c, font=font, fill=255)
    
    # Advance width
    adv = font.getlength(c)
    
    # Convert to 4bpp
    stride = (w * BPP + 7) // 8
    bitmap = bytearray(stride * h)
    pixels = list(img.getdata())
    for py in range(h):
        for px in range(w):
            val = pixels[py * w + px]
            nibble = (val >> 4) & 0x0F
            byte_idx = py * stride + (px * BPP // 8)
            bit_off = (px % 2) * 4
            bitmap[byte_idx] |= nibble << bit_off
    
    return (bytes(bitmap), w, h, -bbox[0], bbox[1] + h, int(adv))

def gen():
    chars = CHARS
    print(f"Rendering {len(chars)} chars at {SIZE}px...")
    
    glyphs = [None]  # index 0 = reserved
    cp_map = {}
    
    for c in chars:
        r = render_char(c, SIZE)
        if r:
            glyphs.append({'char': c, 'cp': ord(c), 'data': r[0], 'w': r[1], 'h': r[2], 'bx': r[3], 'by': r[4], 'adv': r[5]})
            cp_map[ord(c)] = len(glyphs) - 1
        else:
            print(f"  WARN: failed to render U+{ord(c):04X} {c}")
    
    print(f"  Rendered {len(glyphs)-1} glyphs")
    
    # Build ranges
    sorted_cp = sorted(cp_map.items())
    ranges = []
    cur = None
    for cp, gid in sorted_cp:
        if cur is None:
            cur = {'s': cp, 'e': cp, 'items': [(cp, gid)]}
        elif cp == cur['e'] + 1:
            cur['e'] = cp
            cur['items'].append((cp, gid))
        else:
            ranges.append(cur)
            cur = {'s': cp, 'e': cp, 'items': [(cp, gid)]}
    if cur:
        ranges.append(cur)
    
    print(f"  {len(ranges)} ranges")
    
    # Write C file
    bm_offset = 0
    bm_offsets = {}
    for i, g in enumerate(glyphs):
        bm_offsets[i] = bm_offset
        if g:
            bm_offset += len(g['data'])
    
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(f"/*******************************************************************************\n")
        f.write(f" * Size: {SIZE} px  Bpp: {BPP}  Generated by gen_font.py (Pillow)\n")
        f.write(f" ******************************************************************************/\n\n")
        f.write('#ifdef LV_CONF_INCLUDE_SIMPLE\n#include "lvgl.h"\n#else\n#include "lvgl/lvgl.h"\n#endif\n\n')
        f.write(f"#ifndef LV_FONT_MSHY_16\n#define LV_FONT_MSHY_16 1\n#endif\n#if LV_FONT_MSHY_16\n\n")
        
        # Bitmap
        f.write("static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {\n")
        for i, g in enumerate(glyphs):
            if g is None: continue
            f.write(f"    /* U+{g['cp']:04X} \"{g['char']}\" */\n")
            d = g['data']
            for j in range(0, len(d), 12):
                chunk = d[j:j+12]
                f.write("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",\n")
        f.write("};\n\n")
        
        # Glyph descriptors
        f.write("static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n")
        f.write("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0},\n")
        for i, g in enumerate(glyphs):
            if g is None or i == 0: continue
            f.write(f"    {{.bitmap_index = {bm_offsets[i]}, .adv_w = {g['adv']*16}, .box_w = {g['w']}, .box_h = {g['h']}, .ofs_x = {g['bx']}, .ofs_y = {g['by'] - g['h']}}},\n")
        f.write("};\n\n")
        
        # Cmaps
        f.write("/*---------------------\n *  CHARACTER MAPPING\n *--------------------*/\n\n")
        cmap_lines = []
        for ri, r in enumerate(ranges):
            length = r['e'] - r['s'] + 1
            n_items = len(r['items'])
            if n_items < length:
                # SPARSE
                offsets = [cp - r['s'] for cp, _ in r['items']]
                f.write(f"static const uint16_t unicode_list_{ri}[] = {{\n")
                for j in range(0, len(offsets), 8):
                    f.write("    " + ", ".join(f"0x{o:X}" for o in offsets[j:j+8]) + ",\n")
                f.write("};\n\n")
                cmap_lines.append((ri, r['s'], length, n_items, 'FULL'))
            else:
                cmap_lines.append((ri, r['s'], length, r['items'][0][1], 'TINY'))
        
        f.write("static const lv_font_fmt_txt_cmap_t cmaps[] = {\n")
        gid = 1
        for ri, start, length, data, mode in cmap_lines:
            if mode == 'FULL':
                f.write(f"    {{.range_start = {start}, .range_length = {length}, .glyph_id_start = {gid}, .unicode_list = unicode_list_{ri}, .glyph_id_ofs_list = NULL, .list_length = {data}, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_FULL}},\n")
            else:
                f.write(f"    {{.range_start = {start}, .range_length = {length}, .glyph_id_start = {data}, .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY}},\n")
            gid += length
        f.write("};\n\n")
        
        # Descriptor
        f.write("#if LVGL_VERSION_MAJOR >= 8\nstatic const lv_font_fmt_txt_dsc_t font_dsc = {\n#else\nstatic lv_font_fmt_txt_dsc_t font_dsc = {\n#endif\n")
        f.write("    .glyph_bitmap = glyph_bitmap, .glyph_dsc = glyph_dsc, .cmaps = cmaps,\n")
        f.write("    .kern_dsc = NULL, .kern_scale = 0, .cmap_num = %d, .bpp = %d,\n" % (len(cmap_lines), BPP))
        f.write("    .kern_classes = 0, .bitmap_format = 1,\n")
        f.write("#if LVGL_VERSION_MAJOR == 8\n    .cache = &cache\n#endif\n};\n\n")
        
        # Font
        f.write(f"#if LVGL_VERSION_MAJOR >= 8\nconst lv_font_t {NAME} = {{\n#else\nlv_font_t {NAME} = {{\n#endif\n")
        f.write("    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,\n")
        f.write(f"    .line_height = {SIZE}, .base_line = 0,\n")
        f.write("#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)\n    .subpx = LV_FONT_SUBPX_NONE,\n#endif\n")
        f.write("#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8\n    .underline_position = -1, .underline_thickness = 1,\n#endif\n")
        f.write("    .dsc = &font_dsc,\n")
        f.write("#if LV_VERSION_CHECK(8, 2, 0) || LVGL_VERSION_MAJOR >= 9\n    .fallback = NULL,\n#endif\n")
        f.write("    .user_data = NULL,\n};\n\n#endif /*LV_FONT_MSHY_16*/\n")
    
    print(f"Generated {OUTPUT} ({os.path.getsize(OUTPUT)} bytes)")

if __name__ == "__main__":
    gen()
